name: Test + Sécurité + Build Docker

on:
  push:
  pull_request:

jobs:

  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: pip install -r ./RPG/requirements.txt

    - name: Install RUFF 
      run: pip install ruff  

    - name: Install BANDIT
      run: pip install bandit

    - name: Install SAFETY
      run: pip install safety

    - name: Run pytest
      run: pytest tests/test_main.py
      working-directory: RPG

    - name: Run ruff
      run: ruff check . --fix
    
    - name: Run bandit
      run: bandit -r .
      continue-on-error: true

    - name: Run SAFETY
      run: safety scan


  build:
    needs: tests           
    if: github.ref == 'refs/heads/main'   
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du Repo
      uses: actions/checkout@v3
    
    - name: Build Docker
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/RPG_API:3.0 .

    - name: Trivy
      uses: aquasecurity/trivy-action@0.28.0
      with:
        image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/RPG_API:3.0

    - name: Connexion Dockerhub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Image >>> DockerHub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/RPG_API:3.0
