name: Test + securité

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies
      run:
        pip install -r ./RPG/requirements.txt

    - name: Run pytest
      run: pytest tests/test_main.py
      working-directory: RPG

    - name: Run ruff
      run: ruff check .